name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 1 
    
    - name: Set up Git
      run: |
        git config --global user.name 'Aleš Kučera'
        git config --global user.email 'kuceral4@fel.cvut.cz'
    
#    - name: Replace private code with placeholders
#      run: |
#        python .github/scripts/replace_code.py src/assignments/knn_classifier.py
#        python .github/scripts/replace_code.py src/assignments/linear_classifier.py
#        python .github/scripts/replace_code.py src/assignments/mlp_classifier.py
#        python .github/scripts/replace_code.py src/assignments/tuning.py

#    - name: Remove private files and directories
#      run:
#        rm -rf .github
#        rm -rf data/brute_tests
#
#    - name: Reset commit history
#      run: |
#        rm -rf .git
#        git config --global init.defaultBranch main
#        git init
#        git remote add public https://github.com/urob-ctu/classification.git
#        git add .
#        git commit -m "Commit without history"
    - name: Check the working directory
      run: |
          ls -la

    - name: Filter sensitive data
      run: |
        ".github/scripts/git-filter-repo" \
        --source $(pwd) \
        --target $(pwd) \
        --replace-text ".github/scripts/replace_code" \
        --paths-from-file ".github/scripts/remove_files" \
        --invert-paths \
        --debug

    - name: Check the working directory
      run: |
        ls -la

    - name: Add public repo as remote
      run: |
        git remote add public https://github.com/urob-ctu/classification.git

    - name: Force push to public repo using PAT
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use PAT for authentication
      run: |
        git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/urob-ctu/classification.git main --force