name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 1 
    
    - name: Set up Git
      run: |
        git config --global user.name 'Aleš Kučera Bot'
        git config --global user.email 'kuceral4@fel.cvut.cz'
    
    - name: Replace private code with placeholders
      run: |
        python .github/scripts/replace_code.py src/assignments_solution/knn_classifier.py
        python .github/scripts/replace_code.py src/assignments_solution/linear_classifier.py
        python .github/scripts/replace_code.py src/assignments_solution/mlp_classifier.py
        python .github/scripts/replace_code.py src/assignments_solution/tuning.py

    - name: Remove private files and directories
      run:
        rm -rf .github

    - name: Reset commit history
      run: |
        rm -rf .git
        git config --global init.defaultBranch main
        git init
        git remote add public https://github.com/urob-ctu/classification.git
        git add .
        git commit -m "Initial commit without history"

    - name: Force push to public repo using PAT
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use PAT for authentication
      run: |
        git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/urob-ctu/classification.git main --force