name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 1 
    
    - name: Set up Git
      run: |
        git config --global user.name 'Aleš Kučera's Bot'
        git config --global user.email 'kuceral4@fel.cvut.cz'
    
    - name: Remove sensitive files and folders
      run: |
        git rm -r --cached .github
        git rm -r --cached src/assignments_solution
        git commit -m "Remove private files and folders before sync"

    - name: Reset commit history
      run: |
        rm -rf .git
        git init
        git remote add public https://github.com/urob-ctu/classification.git
        git add .
        git commit -m "Initial commit without history"
    
    - name: Force push to public repo
      run: |
        git push public main --force
        #      env:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
